apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yamatcha/k8s-hands-on.git
    targetRevision: add-status-to-crdmanifest
    path: manifests/argocd-config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
